name: First Workflow
on: 
  push:
    branches:
      - '**'
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: Run a shell command
        run: echo "Hello, World!"
      - name: Multiple commands
        run: |
          echo "This is the first command."
          echo "This is the second command."
  parallel-job-macos:
    runs-on: macos-latest
    steps:
      - name: Run a shell command on macOS
        run: echo "Running on macOS!"
  dependent-job:
    runs-on: windows-latest
    needs: [run-shell-command]
    steps:
      - name: Run a powershell command on Windows
        run: Write-Output "Running on Windows after previous jobs!"
      - name: Error Step
        run: doesnotexist