name: First Workflow
on: 
  push:
    branches:
      - '**'

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: Run a shell command
        run: echo "Hello, World!"
      - name: Multiple commands
        run: |
          echo "This is the first command."
          echo "This is the second command."